# Generated by Django 6.0 on 2026-01-03 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='unit identifier code in the fiplan API', max_length=20, unique=True)),
                ('acronym', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_api', models.CharField(max_length=50, unique=True)),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_cpf', models.CharField(blank=True, max_length=20, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('date_inicied', models.DateField()),
                ('date_return', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, help_text='Valor total da diaria', max_digits=12)),
                ('reason', models.TextField(blank=True, null=True)),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_units', to='integrations.unit')),
            ],
            options={
                'indexes': [models.Index(fields=['date_inicied'], name='integration_date_in_01ca71_idx'), models.Index(fields=['unit'], name='integration_unit_id_5a391f_idx')],
            },
        ),
    ]
