# Generated by Django 6.0 on 2026-04-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_alter_unit_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=14)),
                ('total_liquidado', models.FloatField()),
                ('total_pago', models.FloatField()),
                ('quantidade_pagamentos', models.IntegerField()),
            ],
        ),
    ]
