# Generated by Django 6.0 on 2026-04-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_credor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credor',
            name='total_liquidado',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='credor',
            name='total_pago',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
